export const ErrorCode = {
  PROOF_INVALID: "proof_invalid",
  PROOF_VKEY_MISMATCH: "proof_vkey_mismatch",
  CIRCUIT_ID_MISMATCH: "circuit_id_mismatch",
  CHALLENGE_BINDING_MISMATCH: "challenge_binding_mismatch",
  RECIPIENT_NOT_APPROVED: "recipient_not_approved",
  CAP_EXCEEDED: "cap_exceeded",
  CUMULATIVE_BUDGET_EXCEEDED: "cumulative_budget_exceeded",
  NONCE_ALREADY_USED: "nonce_already_used",
  OFFER_EXPIRED: "offer_expired",
  OFFER_SIGNATURE_INVALID: "offer_signature_invalid",
  CALLBACK_DUPLICATE: "callback_duplicate",
  CALLBACK_AUTH_INVALID: "callback_auth_invalid",
  ILLEGAL_STATE_TRANSITION: "illegal_state_transition",
  REPORT_SCHEMA_INVALID: "report_schema_invalid",
  REPORT_BINDING_MISMATCH: "report_binding_mismatch",
  REQUEST_INVALID: "request_invalid",
  AUTH_INVALID: "auth_invalid",
  CREDIT_REQUEST_SIGNATURE_INVALID: "credit_request_signature_invalid",
  CREDIT_ACCEPTANCE_INVALID: "credit_acceptance_invalid",
  CREDIT_ACCEPTANCE_CONFLICT: "credit_acceptance_conflict",
  LOAN_REGISTRATION_CONFLICT: "loan_registration_conflict",
  LOAN_NOT_FUNDED: "loan_not_funded",
  MISSION_NOT_REPAYABLE: "mission_not_repayable",
  SOURCE_HASH_MISMATCH: "source_hash_mismatch",
  SOURCE_TOO_LARGE: "source_too_large",
  SETTLEMENT_UNCONFIRMED: "settlement_unconfirmed",
  FUNDING_MISMATCH: "funding_mismatch",
  IDEMPOTENCY_CONFLICT: "idempotency_conflict",
  MISSION_POLICY_CONFLICT: "mission_policy_conflict",
  PAYMENT_AUTHORIZATION_INVALID: "payment_authorization_invalid",
  PAYMENT_AUTHORIZATION_MISMATCH: "payment_authorization_mismatch",
  MISSION_POLICY_MISSING: "mission_policy_missing",
  MISSION_POLICY_MISMATCH: "mission_policy_mismatch",
  NOT_FOUND: "not_found",
  INTERNAL_ERROR: "internal_error",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
export interface ErrorResponse { code: ErrorCode; detail: string; }
